javac -d . Carte.java
javac -d . Joueur.java
javac -d . Client.java
javac -d . ClientHandler.java
javac -d . Function.java
javac -d . Server.java
javac -d . Table.java
javac -d . Listener.java
javac -d . Fenetre.java
javac -d . Main.java